version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"

    labels:
      - "dependencies"
      - "go"

    groups:
      all-dependencies:
        patterns:
          - "*"

    reviewers:
     - "gozeloglu"